import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Archivo_Black } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const archivo = Archivo_Black({ subsets: ["latin"],
weight: "400",
variable: "--font-archivo" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        {children}
        </body>
    </html>
  );
}
